### ISSUE TITLE
Citation from High Performance Spark 

### ISSUE THREAD

**Issue by samwarren** [vaquarkhan/vaquarkhan-notes-and-books#1]
I think that you forgot to cite High Performance Spark by Karau and Warren
[here](https://github.com/vaquarkhan/vaquarkhan/wiki/Apache-Spark--Shuffle-hash-join-vs--Broadcast-hash-join) or you just happened to have the same wording when describing the prerequisites for avoiding a spark shuffle hash join (;

**Comment by vaquarkhan** [comment]
sure let me add it
