### ISSUE TITLE
Microservice Architecture eBook

### ISSUE THREAD

**Issue by mattmclartybc** [vaquarkhan/vaquarkhan-notes-and-books#3]
Hi,

The PDF you have posted in the /microservices folder of our "Microservice Architecture" book is sponsored by CA. Can you please remove the PDF and include this download link instead? https://transform.ca.com/API-microservice-architecture-oreilly-book.html 

Thanks, Matt

**Comment by vaquarkhan** [comment]
sure ,thanks Matt

**Comment by vaquarkhan** [comment]
i am not able to find your book , could you please give link in my repo , i will delete and add your link

**Comment by mattmclartybc** [comment]
Thanks Vaquar! Here is a functioning link...
https://www.ca.com/content/dam/ca/us/files/ebook/microservice-architecture-aligning-principles-practices-and-culture.pdf

Matt

**Comment by vaquarkhan** [comment]
done 
https://github.com/vaquarkhan/vaquarkhan/tree/master/microservice
